from pathlib import Path
import unittest

from tools.generate_lua import OUTPUT_PATH, build_data, compact_record, render_lua
from tools.project import canonical_json


class GeneratorTests(unittest.TestCase):
    def test_generator_is_deterministic(self):
        self.assertEqual(render_lua(), render_lua())

    def test_generated_lua_uses_bigbislist_globals(self):
        rendered = render_lua()
        self.assertTrue(rendered.startswith("-- Generated by tools/generate_lua.py"))
        self.assertIn("BigBiSListData = ", rendered)
        self.assertIn('["format"] = 2', rendered)
        self.assertIn('["schemas"] = {', rendered)
        self.assertIn('["gems"] = {', rendered)
        self.assertIn('["gem_sources"] = {', rendered)
        self.assertIn('["enchants"] = {', rendered)
        self.assertIn('["enchant_effects"] = {', rendered)
        self.assertIn('["consumables"] = {', rendered)
        self.assertIn('["leveling_gear"] = {', rendered)
        self.assertIn('["leveling_recommendations"] = {', rendered)
        self.assertIn('["item_fallbacks"] = {', rendered)
        self.assertIn('["uses"] = {', rendered)
        self.assertIn('["tooltip_aliases"] = {', rendered)
        self.assertNotIn('["bis_lists"] = {', rendered)
        self.assertNotIn('["item_stats"] = {', rendered)
        self.assertNotIn('["item_variants"] = {', rendered)
        self.assertNotIn('["leveling"] = {', rendered)
        self.assertNotIn('["recommendation_audit"] = {', rendered)
        self.assertNotIn('["racial_modifiers"] = {', rendered)
        self.assertNotIn('["scoring_profiles"] = {', rendered)
        self.assertNotIn('["overrides"] = {', rendered)
        self.assertNotIn('["credits"] = {', rendered)
        self.assertNotIn("BISTBC", rendered)

    def test_compact_data_preserves_runtime_counts(self):
        data = build_data()
        canonical_items = canonical_json("items")["items"]
        canonical_bis = canonical_json("bis_lists")["lists"]
        canonical_gems = canonical_json("gems")["gems"]
        canonical_enchants = canonical_json("enchants")["enchants"]
        canonical_consumables = canonical_json("consumables")["consumables"]
        canonical_leveling_gear = canonical_json("leveling_gear")["leveling_gear"]
        canonical_recommendations = canonical_json("leveling_recommendations")["leveling_recommendations"]
        canonical_item_stats = canonical_json("item_stats")["item_stats"]
        starter_alias_count = 0
        full_item_ids = {item["id"] for item in canonical_items}
        fallback_item_ids = {
            row["item_id"]
            for row in canonical_recommendations
            if row["item_id"] not in full_item_ids
        }
        stats_item_ids = {item["id"] for item in canonical_item_stats}

        for item in canonical_items:
            seen = set()
            for source in item.get("sources") or []:
                for starter_source in source.get("quest_starter_sources") or []:
                    starter_id = starter_source.get("quest_starter_item_id")
                    if starter_id and starter_id not in seen:
                        starter_alias_count += 1
                        seen.add(starter_id)

        self.assertEqual(data["format"], 2)
        self.assertEqual(len(data["items"]), len(canonical_items))
        self.assertEqual(len(data["item_fallbacks"]), len(fallback_item_ids & stats_item_ids))
        self.assertEqual(data["meta"]["slot_list_count"], len(canonical_bis))
        self.assertEqual(data["meta"]["use_count"], sum(len(row["items"]) for row in canonical_bis))
        self.assertEqual(len(data["uses"]), data["meta"]["use_count"])
        self.assertEqual(len(data["gems"]), len(canonical_gems))
        self.assertEqual(len(data["enchants"]), len(canonical_enchants))
        self.assertEqual(len(data["consumables"]), len(canonical_consumables))
        self.assertEqual(len(data["leveling_gear"]), len(canonical_leveling_gear))
        self.assertEqual(len(data["leveling_recommendations"]), len(canonical_recommendations))
        self.assertEqual(data["meta"]["leveling_gear_count"], len(canonical_leveling_gear))
        self.assertEqual(data["meta"]["leveling_recommendation_count"], len(canonical_recommendations))
        self.assertEqual(data["meta"]["item_fallback_count"], len(data["item_fallbacks"]))
        self.assertEqual(sum(len(row[1]) for row in data["tooltip_aliases"]), starter_alias_count)

    def test_item_fallbacks_cover_recommendation_only_items(self):
        data = build_data()
        schema = data["schemas"]["item_fallback"]
        positions = {key: index for index, key in enumerate(schema)}
        fallbacks = {
            row[positions["id"]]: row
            for row in data["item_fallbacks"]
        }

        self.assertEqual(fallbacks[31701][positions["name"]], "Saboteur's Axe")
        self.assertEqual(fallbacks[31701][positions["quality"]], "uncommon")
        self.assertEqual(fallbacks[29914][positions["name"]], "Hellfire Skiver")
        self.assertEqual(fallbacks[29914][positions["quality"]], "uncommon")
        self.assertNotIn(25762, fallbacks)

    def test_item_fallbacks_preserve_acquisition_sources(self):
        data = build_data()
        schema = data["schemas"]["item_fallback"]
        positions = {key: index for index, key in enumerate(schema)}
        source_schema = data["schemas"]["source"]
        source_positions = {key: index for index, key in enumerate(source_schema)}
        fallbacks = {
            row[positions["id"]]: row
            for row in data["item_fallbacks"]
        }

        vendor_fallback = next(
            row
            for row in fallbacks.values()
            if len(row) > positions["sources"]
            and row[positions["sources"]]
            and any(
                source[source_positions["type"]] in {"vendor", "pvp", "token_turnin"}
                for source in row[positions["sources"]]
            )
        )

        self.assertTrue(vendor_fallback[positions["source_summary"]])
        self.assertTrue(vendor_fallback[positions["primary_source"]])
        self.assertTrue(vendor_fallback[positions["sources"]])

    def test_source_schema_preserves_vendor_detail_fields(self):
        data = build_data()
        schema = data["schemas"]["source"]
        positions = {key: index for index, key in enumerate(schema)}
        compacted = compact_record(
            {
                "type": "vendor",
                "entity_name": "Field Repair Bot 110G",
                "location_area": "Portable",
                "location_note": "Created by engineers",
                "price_copper": 3000,
                "purchase_quantity": 200,
            },
            "source",
        )

        self.assertIn("location_area", schema)
        self.assertIn("location_note", schema)
        self.assertIn("price_copper", schema)
        self.assertIn("purchase_quantity", schema)
        self.assertEqual(compacted[positions["location_area"]], "Portable")
        self.assertEqual(compacted[positions["location_note"]], "Created by engineers")
        self.assertEqual(compacted[positions["price_copper"]], 3000)
        self.assertEqual(compacted[positions["purchase_quantity"]], 200)

    def test_data_lua_is_current_after_generation(self):
        existing = Path(OUTPUT_PATH).read_text(encoding="utf-8").replace("\r\n", "\n")
        self.assertEqual(existing, render_lua())
