from pathlib import Path
import unittest

from tools.generate_lua import OUTPUT_PATH, render_lua


class GeneratorTests(unittest.TestCase):
    def test_generator_is_deterministic(self):
        self.assertEqual(render_lua(), render_lua())

    def test_generated_lua_uses_bigbislist_globals(self):
        rendered = render_lua()
        self.assertTrue(rendered.startswith("-- Generated by tools/generate_lua.py"))
        self.assertIn("BigBiSListData = ", rendered)
        self.assertIn('["gems"] = {}', rendered)
        self.assertIn('["enchants"] = {}', rendered)
        self.assertIn('["consumables"] = {}', rendered)
        self.assertIn('["leveling"] = {}', rendered)
        self.assertNotIn("BISTBC", rendered)

    def test_data_lua_is_current_after_generation(self):
        existing = Path(OUTPUT_PATH).read_text(encoding="utf-8").replace("\r\n", "\n")
        self.assertEqual(existing, render_lua())
