from pathlib import Path
import unittest

from tools.generate_lua import OUTPUT_PATH, build_data, render_lua
from tools.project import canonical_json


class GeneratorTests(unittest.TestCase):
    def test_generator_is_deterministic(self):
        self.assertEqual(render_lua(), render_lua())

    def test_generated_lua_uses_bigbislist_globals(self):
        rendered = render_lua()
        self.assertTrue(rendered.startswith("-- Generated by tools/generate_lua.py"))
        self.assertIn("BigBiSListData = ", rendered)
        self.assertIn('["format"] = 2', rendered)
        self.assertIn('["schemas"] = {', rendered)
        self.assertIn('["gems"] = {', rendered)
        self.assertIn('["gem_sources"] = {', rendered)
        self.assertIn('["enchants"] = {', rendered)
        self.assertIn('["enchant_effects"] = {', rendered)
        self.assertIn('["consumables"] = {', rendered)
        self.assertIn('["uses"] = {', rendered)
        self.assertIn('["tooltip_aliases"] = {', rendered)
        self.assertNotIn('["bis_lists"] = {', rendered)
        self.assertNotIn('["leveling"] = {', rendered)
        self.assertNotIn('["overrides"] = {', rendered)
        self.assertNotIn('["credits"] = {', rendered)
        self.assertNotIn("BISTBC", rendered)

    def test_compact_data_preserves_runtime_counts(self):
        data = build_data()
        canonical_items = canonical_json("items")["items"]
        canonical_bis = canonical_json("bis_lists")["lists"]
        canonical_gems = canonical_json("gems")["gems"]
        canonical_enchants = canonical_json("enchants")["enchants"]
        canonical_consumables = canonical_json("consumables")["consumables"]
        starter_alias_count = 0

        for item in canonical_items:
            seen = set()
            for source in item.get("sources") or []:
                for starter_source in source.get("quest_starter_sources") or []:
                    starter_id = starter_source.get("quest_starter_item_id")
                    if starter_id and starter_id not in seen:
                        starter_alias_count += 1
                        seen.add(starter_id)

        self.assertEqual(data["format"], 2)
        self.assertEqual(len(data["items"]), len(canonical_items))
        self.assertEqual(data["meta"]["slot_list_count"], len(canonical_bis))
        self.assertEqual(data["meta"]["use_count"], sum(len(row["items"]) for row in canonical_bis))
        self.assertEqual(len(data["uses"]), data["meta"]["use_count"])
        self.assertEqual(len(data["gems"]), len(canonical_gems))
        self.assertEqual(len(data["enchants"]), len(canonical_enchants))
        self.assertEqual(len(data["consumables"]), len(canonical_consumables))
        self.assertEqual(sum(len(row[1]) for row in data["tooltip_aliases"]), starter_alias_count)

    def test_data_lua_is_current_after_generation(self):
        existing = Path(OUTPUT_PATH).read_text(encoding="utf-8").replace("\r\n", "\n")
        self.assertEqual(existing, render_lua())
