from __future__ import annotations

import argparse
import sys
from pathlib import Path

if __package__ is None or __package__ == "":
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from tools.project import ADDON_DIR, canonical_json, lua_value, write_text
from tools.validate_data import validate


OUTPUT_PATH = ADDON_DIR / "Data.lua"


def build_data() -> dict:
    classes = canonical_json("classes")["classes"]
    phases = canonical_json("phases")["phases"]
    items = canonical_json("items")["items"]
    bis_lists = canonical_json("bis_lists")["lists"]
    gems = canonical_json("gems")["gems"]
    gem_sources = canonical_json("gem_sources")["gem_sources"]
    enchants = canonical_json("enchants")["enchants"]
    enchant_sources = canonical_json("enchant_sources")["enchant_sources"]
    consumables = canonical_json("consumables")["consumables"]
    leveling = canonical_json("leveling")["leveling"]
    credits = canonical_json("credits")["credits"]
    overrides = canonical_json("overrides")["overrides"]
    manifest = canonical_json("scrape_manifest")

    grouped_lists: list[dict] = []
    class_index: dict[str, dict] = {}

    for class_data in classes:
        grouped_class = {"class": class_data["name"], "specs": []}
        grouped_lists.append(grouped_class)
        class_index[class_data["name"]] = grouped_class

    for row in bis_lists:
        grouped_class = class_index[row["class"]]
        spec_data = next((spec for spec in grouped_class["specs"] if spec["spec"] == row["spec"]), None)
        if spec_data is None:
            spec_data = {"spec": row["spec"], "phases": []}
            grouped_class["specs"].append(spec_data)

        phase_data = next((phase for phase in spec_data["phases"] if phase["phase"] == row["phase"]), None)
        if phase_data is None:
            phase_data = {"phase": row["phase"], "slots": []}
            spec_data["phases"].append(phase_data)

        phase_data["slots"].append(
            {
                "slot": row["slot"],
                "source_url": row["source_url"],
                "items": row["items"],
            }
        )

    return {
        "meta": {
            "addon": "Big BiS List",
            "data_version": "seed-0.1.0",
            "parser_version": manifest["parser_version"],
            "coverage": canonical_json("bis_lists")["coverage"],
            "override_count": len(overrides),
        },
        "classes": classes,
        "phases": phases,
        "items": items,
        "bis_lists": grouped_lists,
        "gems": gems,
        "gem_sources": gem_sources,
        "enchants": enchants,
        "enchant_sources": enchant_sources,
        "consumables": consumables,
        "leveling": leveling,
        "overrides": overrides,
        "credits": credits,
    }


def render_lua() -> str:
    data = build_data()
    return "\n".join(
        [
            "-- Generated by tools/generate_lua.py; do not edit by hand.",
            "BigBiSListData = " + lua_value(data),
            "",
        ]
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate deterministic BigBiSListData Lua.")
    parser.add_argument("--check", action="store_true", help="Fail if the generated output differs from Data.lua.")
    args = parser.parse_args(argv)

    result = validate()
    if not result.ok:
        for error in result.errors:
            print(f"validation error: {error}", file=sys.stderr)
        return 1

    rendered = render_lua()
    if args.check:
        if not OUTPUT_PATH.is_file():
            print(f"{OUTPUT_PATH} does not exist", file=sys.stderr)
            return 1
        existing = OUTPUT_PATH.read_text(encoding="utf-8").replace("\r\n", "\n")
        if existing != rendered:
            print(f"{OUTPUT_PATH} is not up to date", file=sys.stderr)
            return 1
        print(f"{OUTPUT_PATH} is up to date.")
        return 0

    write_text(OUTPUT_PATH, rendered)
    print(f"Wrote {OUTPUT_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
